=== lenpino/sia/sia/WebContent/xml/consultas.dtd
<!ELEMENT consultas (params,strprocs*,conssps*,conssqls*,constxs*)>
	<!ELEMENT params (param)*>
		<!ELEMENT param (type,len)*>
		<!ATTLIST param name ID #REQUIRED>
			<!ELEMENT type (#PCDATA)>
			<!ELEMENT len (#PCDATA)>
			
	<!ELEMENT strprocs (strproc*)>
		<!ELEMENT strproc (inparams?,outparams?)>
		<!ATTLIST strproc strname ID #REQUIRED>
			<!ELEMENT inparams (instrparams*)>
				<!ELEMENT instrparams (#PCDATA)>
			<!ELEMENT outparams (outstrparams*)>
				<!ELEMENT outstrparams (#PCDATA)>
			
	<!ELEMENT conssps (conssp*)>
		<!ELEMENT conssp (considpool,consbean,consstrproc)>
		<!ATTLIST conssp consname ID #REQUIRED>
			<!ELEMENT considpool (#PCDATA)>
			<!ELEMENT consbean (#PCDATA)>
			<!ELEMENT consstrproc (#PCDATA)>
				
	<!ELEMENT conssqls (conssql*)>
		<!ELEMENT conssql (considpoolsql,consbeansql,sql,paramsSQL)>
		<!ATTLIST conssql consnamesql ID #REQUIRED>
			<!ELEMENT considpoolsql (#PCDATA)>
			<!ELEMENT consbeansql (#PCDATA)>
			<!ELEMENT sql (#PCDATA)>
			<!ELEMENT paramsSQL (nomparamSQL*)>
				<!ELEMENT nomparamSQL (#PCDATA)>

	<!ELEMENT constxs (constx*)>
		<!ELEMENT constx (considpooltx,bean,sps)>
		<!ATTLIST constx consnametx ID #REQUIRED>
			<!ELEMENT considpooltx (#PCDATA)>
			<!ELEMENT bean (#PCDATA)>
			<!ELEMENT sps (sp*)>
				<!ELEMENT sp (#PCDATA)>
				<!ATTLIST sp sppar CDATA #REQUIRED>

=== lenpino/sia/sia/WebContent/xml/dbfce.xml
<?xml version="1.0"?>
<!DOCTYPE Consltas SYSTEM "consultas.dtd">
<consultas>
	<params>
		<param name="whichQuery">
			<type>N</type>
			<len>2</len>
		</param>
		<param name="cod_banco">
			<type>C</type>
			<len>10</len>
		</param>
		<param name="web_tasa_acc">
			<type>U</type>
			<len>8</len>
		</param>
		<param name="tiene_apv">
			<type>B</type>
			<len>6</len>
		</param>
	</params>
	<strprocs>
		<strproc strname="sp_ext_oc_key">
			<inparams>
				<instrparams>codprov</instrparams>
				<instrparams>codsuc</instrparams>
				<instrparams>estado</instrparams>
				<instrparams>tipo</instrparams>
				<instrparams>whichQuery</instrparams>
			</inparams>
			<outparams>
				<outstrparams>resultset</outstrparams>
			</outparams>
		</strproc>
	</strprocs>
	<conssps>
		<conssp consname="SPVENTAS">
			<considpool>emitidos</considpool>
			<consbean>StrProcPLSQL</consbean>
			<consstrproc>sp_ext_ic_ventas</consstrproc>
		</conssp>
		<conssp consname="SPMUTUAL">
			<considpool>emitidos</considpool>
			<consbean>StrProcBean30</consbean>
			<consstrproc>sp_LST_InstitucionesPorTipo</consstrproc>
		</conssp>		
	</conssps>
	<conssqls>
		<conssql consnamesql="SQLLOGIN">
			<considpoolsql>emitidos</considpoolsql>
			<consbeansql>SelectJDBCBean</consbeansql>
			<sql>select * from usuario where login=?</sql>
			<paramsSQL>
				<nomparamSQL>usuario</nomparamSQL>
			</paramsSQL>
		</conssql>
	</conssqls>
	<constxs>
		<constx consnametx="TXPUBLICAOC">
			<considpooltx>oracleds</considpooltx>
			<bean>TrxBean</bean>
			<sps>
				<sp sppar="pubOC">sp_ext_ins_orden</sp>
				<sp sppar="pubDO">sp_ext_ins_orden_do</sp>
				<sp sppar="pubDA">sp_ext_ins_orden_da</sp>
				<sp sppar="pubDB">sp_ext_ins_orden_db</sp>
				<sp sppar="pubXD">sp_ext_ins_orden_xd</sp>
				<sp sppar="pubDT">sp_ext_ins_orden_dt</sp>
			</sps>
		</constx>
		<constx consnametx="TXINSDETINP">
			<considpooltx>sqlserver</considpooltx>
			<bean>TrxBean</bean>
			<sps>
				<sp sppar="detInp">sp_INS_Detalle_INPFONASA</sp>
			</sps>
		</constx>
	</constxs>
</consultas>
